/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s012puzzlenumber;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Luu Phuong Uyen
 */
public class PuzzleGame extends javax.swing.JFrame {

    /**
     * Creates new form PuzzleGame
     */
    int move = 0;

    public PuzzleGame() {
        initComponents();
        random();
        if (b1.getText().equals("")) {
            lbMoves.setText(Integer.toString(move) + " moves");
            JOptionPane.showMessageDialog(this, "You win!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMoves = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(342, 378));
        setPreferredSize(new java.awt.Dimension(342, 378));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 110, 20, 110));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 40, 10));

        lbMoves.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMoves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbMoves);

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel2.setLayout(new java.awt.GridLayout(0, 3, 15, 15));

        b1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1);

        b2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);

        b3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel2.add(b3);

        b4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel2.add(b4);

        b5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel2.add(b5);

        b6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel2.add(b6);

        b7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel2.add(b7);

        b8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel2.add(b8);

        b9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel2.add(b9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if (b2.getText().equals("")) {
            b2.setText(b1.getText());
            b1.setText("");
            move++;
            lbMoves.setText(Integer.toString(move) + " moves");
            JOptionPane.showMessageDialog(this, "You win!");

        }
        if (b4.getText().equals("")) {
            b4.setText(b1.getText());
            b1.setText("");
            move++;
            lbMoves.setText(Integer.toString(move) + " moves");
            JOptionPane.showMessageDialog(this, "You win!");

        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if (b1.getText().equals("")) {
            b1.setText(b2.getText());
            b2.setText("");
            move++;
        }
        if (b3.getText().equals("")) {
            b3.setText(b2.getText());
            b2.setText("");
            move++;
        }
        if (b5.getText().equals("")) {
            b5.setText(b2.getText());
            b2.setText("");
            move++;
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if (b2.getText().equals("")) {
            b2.setText(b3.getText());
            b3.setText("");
            move++;
        }
        if (b6.getText().equals("")) {
            b6.setText(b3.getText());
            b3.setText("");
            move++;
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if (b1.getText().equals("")) {
            b1.setText(b4.getText());
            b4.setText("");
            move++;
        }
        if (b5.getText().equals("")) {
            b5.setText(b4.getText());
            b4.setText("");
            move++;
        }
        if (b7.getText().equals("")) {
            b7.setText(b4.getText());
            b4.setText("");
            move++;
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if (b2.getText().equals("")) {
            b2.setText(b5.getText());
            b5.setText("");
            move++;
        }
        if (b4.getText().equals("")) {
            b4.setText(b5.getText());
            b5.setText("");
            move++;
        }
        if (b6.getText().equals("")) {
            b6.setText(b5.getText());
            b5.setText("");
            move++;
        }
        if (b8.getText().equals("")) {
            b8.setText(b5.getText());
            b5.setText("");
            move++;
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
      if (b3.getText().equals("")) {
            b3.setText(b6.getText());
            b6.setText("");
            move++;
        }
        if (b5.getText().equals("")) {
            b5.setText(b6.getText());
            b6.setText("");
            move++;
        }
        if (b9.getText().equals("")) {
            b9.setText(b6.getText());
            b6.setText("");
            move++;
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if (b4.getText().equals("")) {
            b4.setText(b7.getText());
            b7.setText("");
            move++;
        }
        if (b8.getText().equals("")) {
            b8.setText(b7.getText());
            b7.setText("");
            move++;
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if (b7.getText().equals("")) {
            b7.setText(b8.getText());
            b8.setText("");
            move++;
        }
        if (b5.getText().equals("")) {
            b5.setText(b8.getText());
            b8.setText("");
            move++;
        }
        if (b9.getText().equals("")) {
            b9.setText(b8.getText());
            b8.setText("");
            move++;
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if (b6.getText().equals("")) {
            b6.setText(b9.getText());
            b9.setText("");
            move++;
        }
        if (b8.getText().equals("")) {
            b8.setText(b9.getText());
            b9.setText("");
            move++;
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        lbMoves.setText("0 move");
        move = 0;
        random();
        if (b1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "You win!");

        }
    }//GEN-LAST:event_btnNextActionPerformed
    public void random() {
        ArrayList btn = new ArrayList();
        int count = 0;
        int value;
        boolean flag;
        while (count < 9) {
            flag = false;
            value = (int) (Math.random() * 9);
            for (int i = 0; i < btn.size(); i++) {
                if (((Integer) btn.get(i)) == value) {
                    flag = true;
                    break;
                }
            }
            if (!flag) {
                btn.add(value);
                count++;
            }
        }
        for (int i = 0; i < btn.size(); i++) {
            if (((Integer) btn.get(i)) == 0) {
                btn.set(i, "");
            }
        }
        b1.setText(btn.get(0).toString());
        b2.setText(btn.get(1).toString());
        b3.setText(btn.get(2).toString());
        b4.setText(btn.get(3).toString());
        b5.setText(btn.get(4).toString());
        b6.setText(btn.get(5).toString());
        b7.setText(btn.get(6).toString());
        b8.setText(btn.get(7).toString());
        b9.setText(btn.get(8).toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuzzleGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbMoves;
    // End of variables declaration//GEN-END:variables
}
