/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Magazine;
import Model.MagazineDB;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class NewMagazine extends javax.swing.JPanel {

    public NewMagazine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        magazineID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        magazineTittle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        publisher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD NEW MAGAZINE");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        jButton1.setText("Cancel");
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 200));
        jPanel2.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Magazine ID");
        jPanel2.add(jLabel7);

        magazineID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                magazineIDFocusLost(evt);
            }
        });
        jPanel2.add(magazineID);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Magazine Tittle");
        jPanel2.add(jLabel2);
        jPanel2.add(magazineTittle);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Publisher");
        jPanel2.add(jLabel3);
        jPanel2.add(publisher);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Price");
        jPanel2.add(jLabel4);
        jPanel2.add(price);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String maID = magazineID.getText().trim();
        String title = magazineTittle.getText().trim();
        String publ = publisher.getText().trim();
        float pr = Float.parseFloat(price.getText().trim());
        if (MagazineDB.getMagazine(maID) != null) {
            JOptionPane.showMessageDialog(this, "Magazine ID existed!");
        } else if (String.valueOf(maID).equals("") || String.valueOf(title).equals("") 
                || String.valueOf(publ).equals("") || String.valueOf(pr).equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all required fields!");
        } else {
            Magazine mg = new Magazine(maID, title, publ, pr);
            if (MagazineDB.newMagazine(mg)) {
                JOptionPane.showMessageDialog(this, "Add new magazine successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed!");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void magazineIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_magazineIDFocusLost
        // TODO add your handling code here:
        String mid = magazineID.getText();
        if (!mid.matches("M[0-9][0-9][0-9]")) {
            JOptionPane.showMessageDialog(this, "Wrong format of Magazine ID: M000!");
            magazineID.setText("");
            magazineID.requestFocus();
        }
    }//GEN-LAST:event_magazineIDFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField magazineID;
    private javax.swing.JTextField magazineTittle;
    private javax.swing.JTextField price;
    private javax.swing.JTextField publisher;
    // End of variables declaration//GEN-END:variables
}
