USE [ReadBook]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 7/27/2020 4:44:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[BookID] [nvarchar](50) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Author] [nvarchar](200) NULL,
	[Publisher] [nvarchar](50) NULL,
	[Year] [nvarchar](50) NULL,
	[Category] [nvarchar](50) NULL,
	[Language] [nvarchar](50) NULL,
	[Preview] [nvarchar](4000) NULL,
	[Picture] [nvarchar](1000) NULL,
	[Content] [nvarchar](200) NULL,
 CONSTRAINT [PK__Book__3DE0C227E6D8A8A5] PRIMARY KEY CLUSTERED 
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserInformation]    Script Date: 7/27/2020 4:44:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserInformation](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[PassWord] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NULL,
	[UserRight] [bit] NULL
) ON [PRIMARY]

GO
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B001', N'Tuổi Trẻ Đáng Giá Bao Nhiêu', N'Rosie Nguyễn', N'Nhã Nam', N'2018', N'Kỹ Năng Sống', N'Tiếng Việt', N'"Bạn hối tiếc vì không nắm bắt lấy một cơ hội nào đó, chẳng có ai phải mất ngủ.

Bạn trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng.

Bạn có chết mòn nơi xó tường với những ước mơ dang dở, đó không phải là việc của họ.

Suy cho cùng, quyết định là ở bạn. Muốn có điều gì hay không là tùy bạn.

Nên hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống.

Vì sau tất cả, chẳng ai quan tâm."', N'https://sachvui.com/cover/2018/tuoi-tre-dang-gia-bao-nhieu.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-tuoi-tre-dang-gia-bao-nhieu-rosie-nguyen.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B002', N'Cách Học Ngoại Ngữ Nhanh Và Không Bao Giờ Quên', N'Gabriel Wyner', N'Skybooks', N'2019', N'Học Ngoại Ngữ', N'English', N'Fluent Forever là cách dạy bất cứ ngoại ngữ nào bạn muốn một cách nhanh nhất, hiệu quả nhất. Đây là tài liệu học ngoại ngữ được đánh giá cao nhất hiện nay trên toàn thế giới bới nó không đơn thuần là sách dạy ngoại ngữ mà là một cú đột phá tư duy xuất sắc để làm chủ não bộ. Ứng dụng tri thức về khoa học thần kinh, bạn không cần chờ đến một sự may mắn tình cờ hay cần mẫn quá sức để đưa thông tin cần thiết vào não bộ. Những gì bạn muốn sẽ thuận với tự nhiên lưu vào bộ nhớ. Bởi thế, không phải ngẫu nhiên, trang web fluent-forever.com trở thành một “hiện tượng mạng”, dạy ngoại ngữ cho 1,5 triệu người trên toàn thế giới và khiến hàng triệu người ham thích thử thách tư duy tìm đến.', N'https://sachvui.com/cover/2018/cach-hoc-ngoai-ngu-nhanh-va-khong-bao-gio-quen.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-cach-hoc-ngoai-ngu-nhanh-va-khong-bao-gio-quen-gabriel-wyner.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B003', N'Mặc Kệ Thiên Hạ - Sống Như Người Nhật', N'Mari Tamagawa', N'Skybooks', N'2018', N'Kỹ Năng Sống', N'Tiếng Việt', N'Đã đến lúc bạn nên dừng tìm kiếm sự an ủi ở người khác, hoặc chờ đợi sự giúp đỡ từ một ai đó. Bởi an ủi hay giúp đỡ về mặt cảm xúc đôi khi giống như con dao hai lưỡi. Nó có thể giúp bạn chống đỡ lo âu hay muộn phiền nhất thời, nhưng lại đẩy bạn chìm sâu hơn vào những cảm xúc tiêu cực đó. Giống như một đứa trẻ khi vấp ngã, bạn mong đợi một sự xoa dịu từ người lớn, mà quên mất rằng sự “hỗ trợ” ấy chỉ càng khiến bạn mãi chẳng thể nào “biết đi”.
', N'https://sachvui.com/cover/2018/mac-ke-thien-ha-song-nhu-nguoi-nhat.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-mac-ke-thien-ha-song-nhu-nguoi-nhat-mari-tamagawa.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B004', N'Nhà Giả Kim', N'Paulo Coelho', N'Nhã Nam', N'2020', N'Kỹ Năng Sống', N'Tiếng Việt', N'Tiểu thuyết Nhà giả kim của Paulo Coelho như một câu chuyện cổ tích giản dị, nhân ái, giàu chất thơ, thấm đẫm những minh triết huyền bí của phương Đông. Trong lần xuất bản đầu tiên tại Brazil vào năm 1988, sách chỉ bán được 900 bản. Nhưng, với số phận đặc biệt của cuốn sách dành cho toàn nhân loại, vượt ra ngoài biên giới quốc gia, Nhà giả kim đã làm rung động hàng triệu tâm hồn, trở thành một trong những cuốn sách bán chạy nhất mọi thời đại, và có thể làm thay đổi cuộc đời người đọc.', N'https://sachvui.com/cover/2015/Nha-Gia-Kim.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2016/pdf/Sachvui.Com-Nha-Gia-Kim.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B006', N'Mắt Biếc', N'Nguyễn Nhật Ánh', N'Nhà xuất bản Trẻ', N'2019', N'Truyện Tình Cảm', N'Tiếng Việt', N'Một tác phẩm được nhiều người bình chọn là hay nhất của nhà văn này. Một tác phẩm đang được dịch và giới thiệu tại Nhật Bản (theo thông tin từ các báo)… Bởi sự trong sáng của một tình cảm, bởi cái kết thúc rất, rất buồn khi suốt câu chuyện vẫn là những điều vui, buồn lẫn lộn (cái kết thúc không như mong đợi của mọi người). Cũng bởi, mắt biếc… năm xưa nay đâu (theo lời một bài hát).', N'https://sachvui.com/cover/2015/mat-biec.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-ky-nang-di-truoc-dam-me-cal-newport.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B007', N'Tự Học Tiếng Anh Hiệu Quả', N'Nguyễn Thị Hà Bắc', N'Nhà xuất bản Trẻ', N'2020', N'Học Ngoại Ngữ', N'English', N'Nếu  như bạn  mong  muốn  giao  tiếp  tiếng  Anh  thành  thạo,  chuyên nghiệp từ 3 tới 6 tháng thì cuốn sách này sẽ làm bạn thất vọng. Thực tế cho thấy chưa có ai mới bắt đầu học tiếng  Anh có thể giao tiếp được trôi chảy trong thời gian từ 3 – 6 tháng. Đó là ảo tưởng. Nhưng nếu như bạn đang tìm kiếm làm như thế nào có thể sử dụng tiếng Anh giao tiếp thành thạo, chuyên nghiệp trong 1 năm tới thì xin chúc mừng  bạn.  Tôi tin rằng  những  bí  mật  được tiết  lộ  trong  cuốn sách này sẽ làm bạn thỏa mãn với điều đó. 

Có rất nhiều người học tiếng Anh lâu năm nhưng vẫn không giao tiếp được. Có những người học tiếng Anh tại các trung tâm khác nhau nhưng vẫn không giao tiếp được. Hầu hết chúng ta học ngoại ngữ gần 12 năm cũng không giao tiếp được. Phải chăng có điều gì đó mà những người chúng ta còn thiếu?', N'https://sachvui.com/cover/2019/tu-hoc-tieng-anh-hieu-qua.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-tu-hoc-tieng-anh-hieu-qua-nguyen-thi-ha-bac.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B010', N'Chúa Ơi Chàng Muốn Lấy Con', N'Agnes Abécassis', N'Hội Nhà Văn', N'2013', N'Truyện Cười - Tiếu Lâm', N'Tiếng Việt', N'Truyện Cười - Tiếu Lâm', N'https://sachvui.com/cover/2015/chua-oi-chang-muon-lay-con.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2017/pdf/Sachvui.Com-chua-oi-chang-muon-lay-con-agnes-abecassis.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B011', N'Sách Của Bạn Tôi', N'Anatole France', N'NXB Kim Đồng', N'2020', N'Truyên Teen - Tuổi Học Trò', N'Tiếng Việt', N'Sách của bạn tôi là một trong những tác phẩm tự truyện nổi tiếng của Anatole France viết về thời thơ ấu. Câu chuyện của chú bé Pierre với những mối quan hệ tuổi thơ, những kỷ niệm với bạn đồng trang lứa, với giáo viên và trường lớp, những nhân vật đã đi qua tuổi thơ của chú như một ánh sáng huyền diệu kỳ bí in vào tâm hồn chú một hình ảnh đẹp không thể phai mờ.

Phần tiếp theo của câu chuyện là khi chú bé Pierre lớn, lúc này Pierre đã trở thành cha và để ý quan sát những cử chỉ, động tác của cô con gái nhỏ.

Với Sách của bạn tôi, Anatole France đã viết nên những trang văn tuyệt tác, rất duyên dáng và hấp dẫn, đầy những nhạc điệu gợi cảm… khiến người ta không thể không dừng lại, im lặng, bồi hồi với những kỷ niệm đẹp nơi tuổi thơ đã đi qua.

Năm 1921, Anatole France được trao giải Nobel Văn học bởi “những tác phẩm xuất sắc mang phong cách tinh tế, chủ nghĩa nhân văn sâu sắc và khí chất Gauloir đích thực”.', N'https://sachvui.com/cover/2018/sach-cua-ban-toi-anatole-france.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-sach-cua-ban-toi-anatole-france.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B012', N'
Siêu Lý Tình Yêu', N'Vladimir Soloviev', N'NXB Kim Đồng', N'2018', N'Triết Học', N'Tiếng Việt', N'Soloviev chỉ ra 5 loại quan hệ nam nữ với loại quan hệ nam nữ có tình yêu gắn với lý tưởng hóa đối tượng yêu, làm chúng ta khi yêu mang bản nguyên thần thánh. Tình yêu nam - nữ tuyệt đích sẽ bất tử hóa tất cả bởi tình yêu chuyên trở sự sống vĩnh cửu cho cái mình yêu, tái sinh vĩnh viễn trong cái đẹp.


Đó là luận điểm về tình yêu qua các tác phẩm trứ danh: Siêu lý tình yêu (1892-1893), Chiến tranh và hòa bình, Biện minh cái thiện của Vladimir Solovyev, người nhà văn, đại triết gia Nga - người đặt nền móng cho Triết học Tình yêu châu Âu.', N'https://sachvui.com/cover/2018/sieu-ly-tinh-yeu.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-sieu-ly-tinh-yeu-vladimir-soloviev.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B013', N'
Những Huyền Thoại', N'Roland Barthes', N'Hội Nhà Văn', N'2017', N'Triết Học', N'Tiếng Việt', N'1(current)2›
Cuốn sách gồm hai phần. Phần đầu lấy tiêu đề trùng với nhan đề của sách là “Những huyền thoại” tập hợp 53 bài ông viết từ 1954 đến 1956 về các vấn đề thời sự hàng ngày hết sức đa dạng ông quan sát và nghiền ngẫm trong xã hội Pháp; chất liệu của những bài viết ấy có thể là một bộ phim, một bài báo, một tấm ảnh ở trang bìa tờ tạp chí, một cuộc triển lãm... Phần thứ hai mang tiêu đề “Huyền thoại, ngày nay...” (Le mythe, aujourd’hui...) có thể xem như lời hậu bạt dài khép lại cuốn sách.', N'https://sachvui.com/cover/2018/nhung-huyen-thoai.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-nhung-huyen-thoai-roland-barthes.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B014', N'Bàn Về Tinh Thần Pháp Luật', N'Montesquieu', N'Hội Nhà Văn', N'2016', N'Triết Học', N'Tiếng Việt', N'"Bàn về tinh thần pháp luật" là tuyệt tác triết học của Montesquieu, là một trong những tác phẩm vĩ đại trong lịch sử triết học chính trị và trong lịch sử luật học.  Mục đích cuốn sách, như chính tác giả đã nêu, là: Trình bày những nguyên nhân quyết định nền pháp lý cho mỗi quốc gia; trình bày sự phù hợp cần thiết giữa luật lệ và chế độ cai trị của một nước; trình bày những quan hệ giữa các luật lệ với nhau. Ông đã phải mất gần 20 năm cho tác phẩm này.', N'https://sachvui.com/cover/2018/ban-ve-tinh-than-phap-luat.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-ban-ve-tinh-than-phap-luat-montesquieu.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B015', N'
Con Người Trong Thế Giới Tinh Thần', N'Nikolai Alexandrovich Berdyaev', N'Nhã Nam', N'2016', N'Triết Học', N'Tiếng Việt', N'N. A. Berdyaev cho rằng không thể có bản diện cá nhân nếu không tồn tại cái đứng cao hơn nó, nếu không có cái thế giới trên núi để bản diện cá nhân leo lên. Hiện hữu của bản diện cá nhân đòi hỏi phải có hiện hữu của các giá trị siêu cá biệt. Từ nhân học ông đi đến hiện hữu của Thượng Đế. Nhưng N. A. Berdyaev bác bỏ quan niệm Thượng Đế như sức mạnh thống trị thế gian và sử dụng con người vốn là tạo vật của mình như phương tiện để tự vinh danh mình. Ông quan niệm một Thượng Đế-bản diện cá nhân mong mỏi con người-bản diện cá nhân đáp lại lời hiệu triệu của Người và Người có thể giao lưu tình yêu với nó', N'https://sachvui.com/cover/2018/con-nguoi-trong-the-gioi-tinh-than.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-con-nguoi-trong-the-gioi-tinh-than-nikolai-alexandrovich-berdyaev.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B017', N'Vĩ Đại Do Lựa Chọn', N'Jim Collins - Morten T. HansenJim Collins - Morten T. Hansen', N'Hội Nhà Văn', N'2019', N'Kinh Tế - Quản Lý', N'Tiếng Việt', N'Jim Collins là tác giả của hai đầu sách nổi tiếng - Từ tốt đến vĩ đại và Xây dựng để trường tồn. Cùng với phương pháp nghiên cứu như hai cuốn đầu tiên, trong quyển sách này, Jim Collins cùng với Morten T. Hansen đi tìm câu trả lời cho câu hỏi, tại sao các công ty vĩ đại vẫn trường tồn trong những lúc khó khăn, hỗn loạn. Qua rất nhiều năm nghiên cứu khoa học từ những công ty và các lãnh đạo hàng đầu, hai tác giả rút ra được kết luận rằng: Chúng tôi không tin cuộc sống sẽ trở nên tốt đẹp hơn hay có một phép nhiệm mầu và đoán định được tương lai, nhưng có thể nói những tác động phức tạp, toàn cầu hóa và công nghệ đang thúc đẩy thay đổi và càng dễ bị thay đổi hơn bao giờ hết. Chúng tôi cảm thấy trấn tĩnh vì chúng tôi đã hiểu hơn phải có những gì để sống sót, lèo lái và chiến thắng. Theo chúng tôi, trường tồn và tiêu vong phụ thuộc vào những hành động của chúng ta hơn là những gì mà thế giới gây cho chúng ta; và sự vĩ đại không chỉ là một cuộc chinh phục về kinh doanh, nó là cuộc chinh phục của con người.', N'https://sachvui.com/cover/2019/vi-dai-do-lua-chon.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-vi-dai-do-lua-chon-jim-collins-morten-t-hansen.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B018', N'Kinh Nghiệm Thành Công Của Ông Chủ Nhỏ', N'Lão Mạc', N'NXB Văn Học', N'2018', N'Kinh Tế - Quản Lý', N'Tiếng Việt', N'Kinh Nghiệm Thành Công Của Ông Chủ Nhỏ là một cuốn sách có nội dung khác biệt với những cuốn sách kinh doanh thông thường khác, có thể sẽ giúp ích được cho những bạn trẻ đã và đang dấn thân vào lĩnh vực kinh doanh. Trong cuốn sách này, trước tiên, tác giả nêu ra tình huống, sau đó đi sâu phân tích, đưa ra những luận điểm về những tình tiết quan trọng trong câu chuyện và đề cập tới những lĩnh vực có thể ứng dụng luận điểm đó. Những câu chuyện mà tác giả viết ra không được phân loại theo phương thức quản lí kinh doanh mà dựa theo đặc điểm cách làm của doanh nghiệp. Và đặc biệt, đó không phải là những câu chuyện quen thuộc từng được đề cập trong giáo trình thương mại, mà phần lớn là những điều tâm đắc và những trải nghiệm của chính tác giả.', N'https://sachvui.com/cover/2019/kinh-nghiem-thanh-cong-cua-ong-chu-nho.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-kinh-nghiem-thanh-cong-cua-ong-chu-nho-lao-mac.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B020', N'Chiêu Bài Quản Lý Vàng Của Bill Gates', N'Thương Mỗ', N'Nhà xuất bản Trẻ', N'2018', N'Kinh Tế - Quản Lý', N'Tiếng Việt', N'Bill Gates là người sáng lập ra công ty Microsoft, công ty hàng đầu chuyên cung cấp phần mềm cho máy tính. Ông nguyên là Tổng Giám đốc và CEO của công ty Microsoft. Ông là người nổi tiếng trên thế giới. Ông đã biến lĩnh vực phần mềm trở thành một thần thoại, đã tạo ra một vương quốc phần mềm kỳ diệu bằng cả cuộc đời mình.', N'https://sachvui.com/cover/2018/chieu-bai-quan-ly-vang-cua-bill-gates.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-chieu-bai-quan-ly-vang-cua-bill-gates-thuong-mo.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B021', N'
Hành Trình Của Linh Hồn', N'Michael Duff Newton', N'NXB Kim Đồng', N'2018', N'Văn Hóa - Tôn Giáo', N'Tiếng Việt', N'Bạn có sợ chết không? Bạn có tự hỏi điều gì sẽ xảy ra sau khi bạn chết không? Có thể nào bạn có một linh hồn đến từ đâu đó và sẽ trở về đó sau khi thân xác bạn chết đi, hay đó chỉ là một điều ước ao vì bạn quá sợ hãi?', N'https://sachvui.com/cover/2019/hanh-trinh-cua-linh-hon.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-hanh-trinh-cua-linh-hon-michael-duff-newton.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B022', N'Nhân Quả', N'Nguyễn Chu Phác', N'Nhà xuất bản Trẻ', N'2019', N'Văn Hóa - Tôn Giáo', N'Tiếng Việt', N'Vũ trụ, vạn vật không phải tuần hành, biến dịch một cách tự nhiên, vô lý, mà tuân theo một cái luật chung, luật đó là luật nhân quả. Luật này không phải do một đấng nào, xã hội nào đặt ra, mà là một luật thiên nhiên âm thầm, lặng lẽ, nhưng đúng đắn vô cùng. Cuốn sách Nhân Quả của Nguyễn Chu Phác sẽ cung cấp cho bạn đọc cái nhìn tổng quan và những ví dụ có thật, sinh động về luật nhân quả theo triết lý của đạo Phật.', N'https://sachvui.com/cover/2018/nhan-qua.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-nhan-qua-nguyen-chu-phac.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B023', N'Bên Rặng Tuyết Sơn', N'Swami Amar Jyoti', N'Nhà xuất bản Trẻ', N'2020', N'Văn Học Việt Nam', N'Tiếng Việt', N'Bên Rặng Tuyết Sơn là quyển sách mới trong bộ sách khoa học tâm linh nổi tiếng của dịch giả Nguyên Phong. Khơi nguồn từ vùng núi Himalaya xa xôi và vùng đồng bằng Ấn Độ, Bên Rặng Tuyết Sơn mang đến cho bạn đọc những sự thật vĩ đại về tâm linh và vai trò của việc làm chủ tâm linh cũng như làm chủ số phận. Tác phẩm còn khơi dậy những giá trị cao đẹp như: Tính trung thực, trái tim bao dung, lòng trắc ẩn, sự thông thái, lòng tín ngưỡng và tình yêu bao la.', N'https://sachvui.com/cover/2018/ben-rang-tuyet-son.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-ben-rang-tuyet-son-swami-amar-jyoti.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B024', N'Ván Bài Lật Ngửa', N'Nguyễn Trương Thiên Lý', N'Nhà xuất bản Trẻ', N'2019', N'Văn Học Việt Nam', N'Tiếng Việt', N'Trong ngày toàn thắng vĩ đại 30 tháng 4 nǎm 1975 kết thúc quá trình phấn đấu lâu dài của dân tộc có phần hy sinh đóng góp thầm lặng của những chiến sĩ tình báo. Mặt trận mà họ chiến đấu hầu hết không nổ súng, lại là nơi thử thách nghiêm khắc nhất bộ thần kinh cùng các đòi hỏi cao lòng dũng cảm, trí thông minh, sự nhạy bén.', N'https://sachvui.com/cover/2018/van-bai-lat-ngua.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-van-bai-lat-ngua-nguyen-truong-thien-ly.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B025', N'Dứt Tình', N'Vũ Trọng Phụng', N'Nhà xuất bản Trẻ', N'2018', N'Văn Học Việt Nam', N'Tiếng Việt', N'Vũ Trọng Phụng là một nhà văn, nhà báo, một cây bút phóng sự với nhiều bài tiêu biểu. Năm 1930, ông có bài đăng trên Ngọ báo, nhưng lúc này tên tuổi ông chưa thực sự được chú ý trong giới văn học Việt Nam. Mãi đến 1931, vở kịnh Không một tiếng vang ra đời, thì mới bắt đầu gây được sự chú ý của bạn đọc. Năm 1934, Vũ Trọng Phụng có tiểu thuyết đầu tay "Dứt tình" (còn có tên khác là Bởi không duyên kiếp) đăng trên tờ Hải Phòng tuần báo. Với tiểu thuyết này, Vũ Trọng Phụng được khen là “ngòi bút tả chân thực đã khéo léo”."Dứt tình" là cuốn tiểu thuyết mang tư tưởng định mệnh siêu hình.', N'https://sachvui.com/cover/2018/dut-tinh.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-dut-tinh-vu-trong-phung.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B026', N'Cuộc Đời Ngoài Cửa', N'Nguyễn Danh Lam', N'Nhà xuất bản Trẻ', N'2018', N'Văn Học Việt Nam', N'Tiếng Việt', N'Trong vai một người viết tiểu thuyết, Nguyễn Danh Lam hẳn là mẫu nhà văn không thích, thậm chí rất dị ứng, việc cưng nựng chiều chuộng các nhân vật của mình. Từ những “Bến vô thường”, “Giữa vòng vây trần gian”, đến “Giữa dòng chảy lạc”, đã là thế. Và rồi đến cuốn tiểu thuyết mới nhất này, vẫn là thế. Nguyễn Danh Lam không thèm hạ cố ban cho nhân vật một danh tính rõ ràng. Cũng rất hiếm khi nhà văn gắn cho họ những nét phẩm chất tính cách hoặc những năng lực cá nhân trên mức trung bình. Đã vậy, anh lại hay đẩy các nhân vật vào những cảnh huống trớ trêu, những trạng thái sinh tồn nếu không bi đát thì cũng dở khóc dở cười.', N'https://sachvui.com/cover/2018/cuoc-doi-ngoai-cua.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-cuoc-doi-ngoai-cua-nguyen-danh-lam.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B027', N'
Ngày Vui', N'Đặng Trần Huân', N'Nhã Nam', N'2018', N'Văn Học Việt Nam', N'Tiếng Việt', N'
Ðặng Trần Huân sinh ngày 07 tháng 6 năm 1929 tại Bắc Ninh, cựu thiếu tá QLVNCH, làm việc tại Cục Tâm Lý Chiến, ngành thông tin báo chí. Khởi viết năm 1953. Ông là tác giả tập truyền cười nổi tiếng " Chuyện Cấm Đàn Bà I & II (1969, 1970)" , rồi Chuyện Vợ Chồng (1970). 

Sau năm 1975, ông đi học tập cải tạo, và định cư tại Hoa Kỳ từ năm 1992. Mặc dù qua Mỹ muộn màng, sức khỏe sa sút, tuổi tác lại cao nhưng nhà văn Đặng Trần Huân đã cầm bút trở lại, và viết một cách hăng say, qua nhiều thể tài khác nhau. Chỉ trong vòng 5 năm mà ông đã xuất bản 3 tác phẩm, gồm có: Hành Trình Một Hát Ô (bút ký, 1995), Những Người Thích Dấu Huyền (1998), và Chữ Nghĩa Bề Bề (chuyện văn nghệ, 2000). ', N'https://sachvui.com/cover/2018/ngay-vui.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-ngay-vui-dang-tran-huan.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B028', N'
Đêm Hội Long Trì', N'Nguyễn Huy Tưởng', N'Hội Nhà Văn', N'2018', N'Văn Học Việt Nam', N'Tiếng Việt', N'Đêm hội Long Trì là một cuốn tiểu thuyết lịch sử của nhà văn Nguyễn Huy Tưởng.

Tác phẩm chọn một thời đoạn lịch sử điển hình cho sự suy thoái và phân rã của xã hội, nên có nhiều đất đai cho việc khai thác các mâu thuẫn và xung đột; cho sự mở rộng và đào sâu vào thế giới nhân vật; cho sự triển khai các mạch truyện và chủ đề; và cho sự gửi gắm nhiều ý tưởng rút từ lịch sử, trong gắn nối và soi sáng các vấn đề của thời hiện tại.', N'https://sachvui.com/cover/2017/dem-hoi-long-tri.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2017/pdf/Sachvui.Com-dem-hoi-long-tri-nguyen-huy-tuong.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B029', N'Vi Sinh Vật Vi Tính', N'Nick Arnold - Tony De Saulles', N'Hội Nhà Văn', N'2020', N'Khoa Học - Kỹ Thuật', N'Tiếng Việt', N'Cuốn sách thuộc bộ Horrible Science, được trình bày bằng giọng văn và các minh họa hài hước quen thuộc của hai tác giả Nick Arnold và Tony De Saulles giúp bạn dễ dàng làm quen với kiến thức cơ bản nhất liên quan đến các loại vi khuẩn vi sinh.

Những hình vẽ và lời giản dị dễ hiểu – như những đoạn truyện tranh  hấp dẫn giúp bạn dễ tưởng tượng ra thế giới của những “động vật” tí hon, cùng với tên tuổi những nhà bác học trong ngành, những kết luận khoa học và nhất là những lời khuyên thực tế, hữu hiệu vô giá, những cảnh báo quan trọng cho lối sống hiện đại … Và nhờ thế mà cuốn sách được nhiều giải thưởng về sách khoa học dành cho thiếu nhi và được đông đảo bạn đọc từ trẻ em đến người lớn tìm đọc.', N'https://sachvui.com/cover/2019/horrible-science-vi-sinh-vat-vi-tinh.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-horrible-science-vi-sinh-vat-vi-tinh-nick-arnold-tony-de-saulles.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B030', N'Người Hy Lạp Huyền Thoại', N'Terry Deary', N'Hội Nhà Văn', N'2018', N'Khoa Học - Kỹ Thuật', N'Tiếng Việt', N'Rõ ràng là người Hy Lạp cổ đại là một cộng đồng rất thoải mái. Con trai chỉ bắt đầu đi học khi lên bảy tuổi, còn con gái thì không cần phải học luôn. Thế nên, để có việc gì đó để làm, trẻ con Hy Lạp sáng chế ra đủ loại trò chơi vui nhộn, còn người lớn thì phát minh ra cuộc thi Olympic để bắt đàn ông chạy đua với "không mảnh vải che thân." Nhưng cuốn sách này sẽ cho bạn thấy, mọi chuyện không phải lúc nào cũng vui nhộn thế đâu... và có một số việc người Hy Lạp làm thật sự là hơi hơi... rùng mình!', N'https://sachvui.com/cover/2019/horrible-histories-nguoi-hy-lap-huyen-thoai.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-horrible-histories-nguoi-hy-lap-huyen-thoai-terry-deary.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B031', N'Bờ Biển Bụi Bờ', N'Anita Ganeri', N'NXB Kim Đồng', N'2018', N'Khoa Học - Kỹ Thuật', N'Tiếng Việt', N'Tạm biệt những bài địa lý chán phèo để đến với Bờ biển bụi bờ!
- Kinh ngạc! Trước con đường của người khổng lồ hùng vĩ!
- Tái mặt! Khi lướt trên những con sóng dữ tợn.
- Rợn người! Khi đi ngang Bờ biển xương khô.
Và nếu bạn vẫn chưa rùng mình thì xin mời đến ngọn hải đăng kỳ quái, hoặc xem con ốc biển cưỡi sóng như thế nào. Toàn những chuyện hấp dẫn với bạn. Và địa lý cũng chưa bao giờ rùng rợn đến thế!

', N'https://sachvui.com/cover/2019/horrible-geography-bo-bien-bui-bo.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-horrible-geography-bo-bien-bui-bo-anita-ganeri.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B032', N'Nhìn Lên Những Chòm Sao', N'Trần Thời', N'NXB Kim Đồng', N'2020', N'Khoa Học - Kỹ Thuật', N'Tiếng Việt', N'Ở các nước có ngành khoa học không gian tiến bộ trên thế giới thì bộ môn Thiên Văn học được đưa vào chính khóa trong các trường phổ thông. Môn học này có sức lôi cuốn các em học sinh một cách đặc biệt, vì sự hấp dẫn của nó. Ở đây, các em còn được thực hành quan sát ở những kính thiên văn hiện đại cùng với những mô hình y như thật để dễ hình dung.
Theo thống kê của các nhà nghiên cứu về tuổi thọ của loài người trên thế giới, thì các nhà Thiên Văn học thường có tuổi thọ cao hơn nhiều so với các ngành khoa học khác. Kết luận đó có lẽ cũng hoàn toàn thuyết phục, bởi vì, hình như một khi con người đêm đêm nhìn lên bầu trời đầy sao, thấy vũ trụ mênh mông vô tận, lòng người bình thản lại, không còn háo thắng đua tranh. Con người cảm nhận được sự nhỏ nhoi của mình, do đó gạt bỏ những mối ưu tư và sống lâu hơn.', N'https://sachvui.com/cover/2018/nhin-len-nhung-chom-sao.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-nhin-len-nhung-chom-sao-tran-thoi.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B033', N'
Bí Mật Vũ Trụ', N'Trần Thoại Lan', N'Nhã Nam', N'2019', N'Khoa Học - Kỹ Thuật', N'Tiếng Việt', N'Hệ Mặt trời không phải là điểm cuối của vũ trụ.

Ngân Hà của chúng ta chỉ là một trong tỉ tỉ các thiên hà.

Gần với ta nhất, thiên hà Tiên Nữ cũng cách hơn 2 triệu năm ánh sáng, tức ánh sáng cũng phải truyền suốt 2 triệu năm mới đến nơi.

Viết về "vũ trụ" - khoảng không vô tận luôn thách thức nhân loại, cuốn sách nhỏ Bí mật vũ trụ hy vọng sẽ đem đến cho bạn đọc một cái nhìn khái quát về lịch sử chinh phục vũ trụ của loài người, từ những luận bàn về Khoảng không bao la kia, cho đến những Vị khách của vũ trụ, và cả việc xây dựng một Thành phố vũ trụ,... Ngoài ra, bạn đọc hẳn sẽ thích thú khi biết... bàn cầu trong tàu không gian có giá hơn... 20 ngàn đô la cũng như nhiều thông tin thú vị khác.', N'https://sachvui.com/cover/2018/bi-mat-vu-tru.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-bi-mat-vu-tru-tran-thoai-lan.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B035', N'Nguồn Cội', N'Dan Brown', N'NXB Kim Đồng', N'2017', N'Phiêu Lưu - Mạo Hiểm', N'Tiếng Việt', N'Trong cuộc hành trình mới nhất của Nguồn cội, ta sẽ được theo chân giáo sư Langdon đến Tây Ban Nha, một đất nước không chỉ có những đội bóng giàu thành tích như Barcelona hay Real Madrid mà còn chứa đựng cả một nền văn hóa và lịch sử có mối liên hệ mạnh mẽ với Công giáo La Mã.

Một quốc gia với 46 di sản thế giới, xếp hàng thứ 3 sau Italy và Trung Quốc, trong đó nhiều di sản được xuất hiện làm bối cảnh cho cuốn sách này.', N'https://sachvui.com/cover/2019/nguon-coi.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-nguon-coi-dan-brown.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B036', N'Viễn Cổ Hành', N'Thi Lạc', N'NXB Kim Đồng', N'2017', N'Phiêu Lưu - Mạo Hiểm', N'Tiếng Việt', N'Lam Nguyệt không ngờ chỉ ngủ một giấc đã đem mình đến thời không khác

Đại thụ chọc trời, các sinh vật chưa hoàn toàn tiến hoá, còn có người nguyên thủy lôi thôi.

Ăn đồ sống, người ở trong động núi, áo rách quần manh

Không gian đâu?Bàn Tay Vàng đâu? Vì cọng lông gì mà không cho ta cái nào? Cuộc sống khốn khổ ở viễn cổ làm sao sống đây?

Hãy xem nữ tử xuyên việt làm sao ở xã hội nguyên thuỷ thành lập Bộ Lạc, bảo vệ ruộng vườn, dẫn dắt người nguyên thủy đi về phía văn minh.', N'https://sachvui.com/cover/2018/vien-co-hanh.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-vien-co-hanh-thi-lac.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B037', N'Hai Vạn Dặm Dưới Đáy Biển', N'Jules Verne', N'NXB Kim Đồng', N'2018', N'Phiêu Lưu - Mạo Hiểm', N'Tiếng Việt', N'Truyện viễn tưởng hay giả tưởng đã có khá nhiều nhà văn trên thế giới thể hiện trong tác phẩm của mình. Cũng là trí tưởng tượng, nhưng khác với truyện cổ tích hay thần thoại, tiểu thuyết giả tưởng thường mang đậm chất hiện thực, sống động.

Hai Vạn Dặm Dưới Đáy Biển là một cuốn tiểu thuyết giả tưởng hiện đại không chỉ dành cho lứa tuổi thiếu nhi mà còn dành cho mọi thế hệ người đọc.

Giáo sư Aronnax cùng anh bạn giúp việc vui tính Conseil là những người say mê khám phá sinh vật biển. Họ đã quyết định khám phá bí mật của quái vật biển. Được sự giúp đỡ của anh chàng thợ săn cá voi siêu hạng Ned Land, họ đã sẵn sàng một cuộc đi săn mà không biết có bao điều nguy hiểm đang chờ đợi mình ở phía trước. Bất ngờ đến với họ khi phát hiện ra con cá voi khổng lồ làm bằng sắt, nhưng tất cả đều không kịp, họ bị bắt làm tù binh trên chiếc tàu của thuyền trưởng Nemo. Và bất đắc dĩ, họ phải tham ra chuyến hành trình trên biển dài ngày. Một thế giới kỳ thú của đại dương đã hiện ra cùng cuộc phiêu lưu của đoàn thám hiểm và thuyền trưởng Nemo: Tham gia chuyến đi săn dưới đáy biển, thoát khỏi cá mập nguy hiểm, chạy trốn những người thổ dân, khai thác kim cương dưới đáy biển, khám phá nhiều vùng đất mới và cuối cùng là mắc kẹt trong núi băng ở Bắc Cực…', N'https://sachvui.com/cover/2018/hai-van-dam-duoi-day-bien.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-hai-van-dam-duoi-day-bien-jules-verne.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B038', N'Người Cá', N'Alexander Romanovich Belyaev', N'Nhã Nam', N'2020', N'Phiêu Lưu - Mạo Hiểm', N'Tiếng Việt', N'Dân làng ven vịnh Plata xôn xao về chuyện con quỷ biển xuất hiện, ai nấy đều sợ đến mức không dám ra khơi. Tin đồn lan tới tận thủ đô Buenos Aires, thu hút giới báo chí chuyên săn lùng những tin giật gân thỏa mãn độc giả hiếu kì. Nhưng vẫn không ai biết thực hư như thế nào. Mọi chuyện có thể sẽ chỉ còn được nghe như là tin đồn nếu một chủ thuyền ngọc trai đang làm ăn trên vịnh là Zurita không cố công tìm kiếm dấu tích của con quỷ để bắt nó mò ngọc trai cho lão. Theo sự lần dấu của Zurita người đọc cũng dần dần khám phá thực sự quỷ biển là ai. Mọi chuyện bắt đầu xấu đi khi chàng “quỷ biển” lần đầu biết yêu!

Câu chuyện được viết hấp dẫn, gợi trí tò mò của bạn đọc. Bên cạnh ước mơ được làm chủ biển cả của con người, truyện còn ca ngợi những tấm lòng nhân hậu, trung thực, phụng sự hết mình cho khoa học để cứu giúp nhân loại và bà mẹ tự nhiên. Truyện đã được dịch ra nhiều thứ tiếng trên toàn thế giới.', N'https://sachvui.com/cover/2018/nguoi-ca.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-nguoi-ca-alexander-romanovich-belyaev.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B039', N'
Mật Mã Maya', N'Brian D''Amato', N'Nhã Nam', N'2016', N'Phiêu Lưu - Mạo Hiểm', N'Tiếng Việt', N'D''amato đã viết lên một câu chuyện phiêu lưu vô cùng tuyệt vời với nhiều chi tiết thú vị về nền văn hoá Maya. Mật mã Maya được coi là một trong những cuốn sách gây bất ngờ nhất năm 2009 về cả chất lượng nội dung lẫn tính giải trí và nó vượt hẳn lên trên những cuốn tiểu thuyết ly kỳ về những bí ẩn khác. Đây là tác phẩm vô cùng thú vị, một cuốn tiểu thuyết có tính sáng tạo phi thường khiến người đọc cuốn theo không ngừng...

Jed DeLanda, một hậu duệ của tộc người Maya sống vào năm 2012, có tài năng thiên bẩm về toán học. Anh ta giành thời gian cho những trò chơi chiến thuật trừu tượng và kiếm được những khoản kếch xù hàng triệu đô la nhờ giao dịch chứng khoán qua mạng với một thứ vũ khí bí mật gọi là "cờ Hiến tế" - một nghi lễ bói toán mà người Maya cổ dùng để tiên liệu sự ra đời và diệt vong của các nền văn minh, hay nói cách khác là một kiểu tiên tri. Nhưng cuộc sống của Jed bị đảo lộn khi ông thầy cũ Taro Mora, nhà khoa học chuyên nghiên cứu lý thuyết trò chơi, và một người thiết kế trò chơi bí hiểm, Marena Park, tham vấn anh ta về một cuốn thư tịch Maya mới được phát hiện- cuốn sách cổ mô tả một ván chơi dự đoán ngày tận thế.

Jed được chọn là người tình nguyện trở về quá khứ... nhưng đã có một sự nhầm lẫn khủng khiếp... Nếu Jed sống sót, anh ta có thể cứu cả thế giới...', N'https://sachvui.com/cover/2015/Mat-Ma-Maya.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2017/pdf/Sachvui.Com-mat-ma-maya.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B040', N'Biểu tượng thất truyền', N'Dan Brown', N'Nhà xuất bản Trẻ', N'2020', N'Phiêu Lưu - Mạo Hiểm', N'Tiếng Việt', N'Bán hết một triệu bản ngay trong buổi phát hành đầu tiên và được xuất bản tại bốn mươi sáu quốc gia, Biểu tượng thất truyền đã tạo nên cơn sốt cho các độc giả trên khắp thế giới. Cuốn sách đưa người đọc song hành cùng nhà biểu tượng học lừng danh Robert Langdon trong cuộc hành trình tới thủ đô nước Mỹ và khám phá bức màn bí ẩn về Hội Tam Điểm - một hội kín có lịch sử lâu đời, cuốn quanh mình vô vàn biểu tượng và truyền thuyết kỳ bí. Trên thực tế, toàn bộ câu chuyện chỉ diễn ra trong vỏn vẹn mười hai tiếng, địa điểm chỉ khoanh vùng ở thủ đô Washington, nhưng không gian và thời gian xây dựng trên ký ức nhân vật lại bao trùm suốt chiều dài lịch sử, tôn giáo, triết học, lý luận, giả kim và nghệ thuật của cả đất nước.', N'https://sachvui.com/cover/2015/bieu-tuong-that-truyen.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2017/pdf/Sachvui.Com-bieu-tuong-that-truyen.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B041', N'Công Nghệ Blockchain', N'Nhiều tác giả', N'Nhã Nam', N'2020', N'Công Nghệ Thông Tin', N'Tiếng Việt', N'Blockchain là chủ đề đang vô cùng nóng trên toàn cầu hiện nay. Nó cùng với Bitcoin và tiền kỹ thuật số trở thành đề tài bàn luận trên rất nhiều mặt báo và trong những cuộc trò chuyện của mọi người. Tuy nhiên, khi nói về blockchain vẫn còn nhiều tranh cãi. Có người lo lắng rằng Bitcoin có thể chỉ là bong bóng, nhiều người cho rằng công nghệ phía sau nó là một sự đột phá, và công nghệ ấy sẽ tiếp tục con đường của mình cho đến khi được chấp nhận và tích hợp với Internet.

Thậm chí, Jamie Dimon, CEO của JP Morgan, người đã gay gắt phản đối Bitcoin và gây ra nhiều lo lắng cho cộng đồng tiền kỹ thuật số cũng đã đồng ý rằng, công nghệ DLT (công nghệ sổ cái phân tán - distributed ledger technology) có tiềm năng rất lớn để thay đổi ngành tài chính và các ngành khác. Hơn nữa, JP Morgan cùng với nhiều ngân hàng đã tiến hành kiểm tra blockchain cho những trường hợp sử dụng khác nhau trong thực tế.

Vậy thì Blockchain thực chất là gì? Nó có thể ứng dụng vào những lĩnh vực nào trong cuộc sống và tại sao nó lại được quan tâm như vậy?', N'https://sachvui.com/cover/2018/cong-nghe-blockchain.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-cong-nghe-blockchain-nhieu-tac-gia.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B042', N'Machine Learning Cơ Bản', N'Vũ Hữu Tiệp', N'Nhà xuất bản Trẻ', N'2020', N'Công Nghệ Thông Tin', N'Tiếng Việt', N'Những năm gần đây, AI - Artificial Intelligence (Trí Tuệ Nhân Tạo), và cụ thể hơn là Machine Learning (Học Máy hoặc Máy Học) nổi lên như một bằng chứng của cuộc cách mạng công nghiệp lần thứ tư (1 - động cơ hơi nước, 2 - năng lượng điện, 3 - công nghệ thông tin). Trí Tuệ Nhân Tạo đang len lỏi vào mọi lĩnh vực trong đời sống mà có thể chúng ta không nhận ra. Xe tự hành của Google và Tesla, hệ thống tự tag khuôn mặt trong ảnh của Facebook, trợ lý ảo Siri của Apple, hệ thống gợi ý sản phẩm của Amazon, hệ thống gợi ý phim của Netflix, máy chơi cờ vây AlphaGo của Google DeepMind, …, chỉ là một vài trong vô vàn những ứng dụng của AI/Machine Learning.

Machine Learning là một tập con của AI. Theo định nghĩa của Wikipedia, Machine learning is the subfield of computer science that “gives computers the ability to learn without being explicitly programmed”. Nói đơn giản, Machine Learning là một lĩnh vực nhỏ của Khoa Học Máy Tính, nó có khả năng tự học hỏi dựa trên dữ liệu đưa vào mà không cần phải được lập trình cụ thể. Bạn Nguyễn Xuân Khánh tại đại học Maryland đang viết một cuốn sách về Machine Learning bằng tiếng Việt khá thú vị, các bạn có thể tham khảo bài Machine Learning là gì?.', N'https://sachvui.com/cover/2018/machine-learning-co-ban.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2019/pdf/Sachvui.Com-machine-learning-co-ban-vu-huu-tiep.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B045', N'Truyện cổ Xyri', N'Nguyễn Huy Thắng', N'NXB Kim Đồng', N'2016', N'Cổ Tích - Thần Thoại', N'Tiếng Việt', N'Syria là một quốc gia ở Tây Á. Cái tên Syria trước kia gồm toàn bộ vùng Levant, trong khi nhà nước hiện đại bao gồm địa điểm của nhiều vương quốc và đế chế cổ, gồm cả nền văn minh Ebla từ thiên niên kỷ thứ ba trước Công Nguyên.', N'https://sachvui.com/cover/2015/Truyen-co-Xyri.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2016/pdf/Sachvui.Com-truyen-co-xyri.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B046', N'Truyện Cổ Di-Gan', N'Marie Voriskova', N'Nhã Nam', N'2016', N'Cổ Tích - Thần Thoại', N'Tiếng Việt', N'Là thợ rèn và thợ làm nồi đồng lưu động - vài người còn nhận là cháu chắc của Tubat - Cain - ngươi làm trò hề và nhất là nhạc công, người Di-Gan đã lưu truyền qua nhiều thời đại một di sản truyền khẩu phong phú. Do đó, những chuyện dân gian tiêu biểu nhất của họ có vẻ quyến rũ độc đáo, bất chấp thời gian. Họ đi qua nhiều xứ, tiếp xúc với nhiều dân tộc, nhưng không bao giờ lẫn lộn nào đó, trái lại hhọ thu thập chất liệu rồi đồng hoá và biến đổi chúng để nuôi dưỡng một di sản huyền thoại vốn đã rất phong phú và đa dạng.', N'https://sachvui.com/cover/2015/Truyen-Co-Di-Gan.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-truyen-co-di-gan.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B047', N'Thần Thoại Hy Lạp', N'Nguyễn Văn Khoả', N'Nhã Nam', N'2018', N'Cổ Tích - Thần Thoại', N'Tiếng Việt', N'"Thần thoại Hy Lạp" bao gồm các truyền thuyết về các vị thần và các vị anh hùng của người Hy Lạp. Bộ sách này hình thành trong một quãng thời gian lịch sử khá dài. Đó là một quá trình lịch sử từ thời kỳ nền văn minh Mycènes (2000 - 1100 TCN) đến những buổi biển diễn, đọc, kể anh hùng ca của Homère trong những ngày hội rồi đến hội diễn bi kịch trong ngày hội Dionysos.


Dù hôm nay, thời đại của niềm tin và tư duy thần thoại đã lùi vào quá khứ, cung điện Olympie của các vị thần hẳn đã dời đến một hành tinh nào khác xa xăm, thì những cái tên như Zeus, Éros, Héraclès… hay Achille vẫn truyền cho loài người những âm hưởng thánh thần để chinh phục ngày mai.


Hầu hết những câu chuyện thần thoại còn lại với độc giả ngày nay đều do những nhà thơ, nhà viết kịch kể lại... Quá trình kể lại cũng đồng thời là quá trình sắp xếp, biên soạn lại, tái tạo các câu chuyện theo một khuynh hướng nào đó.', N'https://sachvui.com/cover/2015/Than-Thoai-Hy-Lap.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2018/pdf/Sachvui.Com-than-thoai-hy-lap.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B048', N'Nghìn Lẻ Một Đêm', N'Nhiều tác giả', N'NXB Kim Đồng', N'2016', N'Cổ Tích - Thần Thoại', N'Tiếng Việt', N'Nghìn lẻ một đêm, tác phẩm vĩ đại bậc nhất của nền văn học A Rập, là một trong những công trình sáng tạo phong phú và hoàn mỹ của nền văn học thế giới.


Để tựa bản dịch tiếng Nga xuất bản năm 1929 ở Sankt Peterburg, Macxim Gorki viết: “Trong số các di tích tuyệt diệu của sáng tác truyền khẩu dân gian, các truyện cổ tích của nàng Sêhêrazát là di tích đồ sộ nhất.


Những truyện cổ tích này thể hiện với mức hoàn hảo kỳ diệu, xu hướng của nhân dân lao động muốn buông mình theo phép nhiệm màu của những ảo giác êm đẹp, theo sự kết hợp phóng khoáng của từ ngữ thể hiện sức mạnh vũ bão của trí tưởng tượng hoa mỹ của các dân tộc phương Đông – người A Rập, người Ba Tư, người Ấn Độ. Công trình dệt gấm bằng từ ngữ này xuất hiện từ thời tối cổ, những sợi tơ muôn màu của nó lan khắp bốn phương, phủ lên trái đất một tấm thảm từ ngữ đẹp lạ lùng.”', N'https://sachvui.com/cover/2015/Nghin-Le-Mot-Dem.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2017/pdf/Sachvui.Com-nghin-le-mot-dem.pdf')
INSERT [dbo].[Book] ([BookID], [Title], [Author], [Publisher], [Year], [Category], [Language], [Preview], [Picture], [Content]) VALUES (N'B049', N'Kho Tàng Truyện Cổ Tích Việt Nam', N'Nguyễn đổng Chi', N'Nhà xuất bản Trẻ', N'2016', N'Cổ Tích - Thần Thoại', N'Tiếng Việt', N'KHO TÀNG TRUYỆN CỔ TÍCH VIỆT NAM,kể từ lần in thứ bảy, in cùng lúc trọn bộ cả năm tập. Rất tiếc, ở những lần in toàn vẹn này tác giả đã không còn được tự mình xem lại bản in thử, như ông đã từng làm việc đó một cách hứng thú và kiên trì trong sáu lần in lẻ tẻ từng tập trước đây.

Tuy nhiên, từ sau khi tập V ra mắt (1982), thân phụ chúng tôi đã có dịp chỉnh lý kỹ cả năm tập, nhất là phần Tổng luận, nhằm chuẩn bị cho một lần in đầy đủ sau này. Chúng tôi cố gắng trung thành với những sửa chữa trực tiếp của ông, kể cả một đôi chỗ ông ủy thác cho tôi soát lại chút ít ít câu chữ, trong khi đọc bộ sách. Mặt khác, trong lần in thứ tư (1972), tác giả có một thay đổi đáng kể trong kết cấu cuốn sách của mình: ông bỏ đi 2 truyện và thay bằng 2 truyện khác để giữ nguyên số lượng 200 truyện.', N'https://sachvui.com/cover/2015/Kho-Tang-Truyen-Co-Tich.jpg', N'https://sachvui.com/sachvui-686868666888/ebooks/2017/pdf/Sachvui.Com-kho-tang-truyen-co-tich.pdf')
SET IDENTITY_INSERT [dbo].[UserInformation] ON 

INSERT [dbo].[UserInformation] ([UserID], [Name], [UserName], [PassWord], [Email], [UserRight]) VALUES (1, N'Nguyễn Duy Hưng', N'Hung132', N'123456', N'hungu21@gmail.com', 0)
INSERT [dbo].[UserInformation] ([UserID], [Name], [UserName], [PassWord], [Email], [UserRight]) VALUES (2, N'Lê Thị Thanh Nhàn', N'Nhan2910', N'123456', N'Nhangu29@gmail.com', 1)
INSERT [dbo].[UserInformation] ([UserID], [Name], [UserName], [PassWord], [Email], [UserRight]) VALUES (3, N'Nguyễn Văn Huy', N'HuyXaki', N'123456', N'Huyxaki163@gmail.com', 0)
INSERT [dbo].[UserInformation] ([UserID], [Name], [UserName], [PassWord], [Email], [UserRight]) VALUES (4, N'Hoàng MY', N'Hoangmy', N'123456', N'HoangMy291@gmail.com', 0)
INSERT [dbo].[UserInformation] ([UserID], [Name], [UserName], [PassWord], [Email], [UserRight]) VALUES (11, N'Lưu Phương Uyên', N'Phuonguyen', N'123456', N'Phuonguyen09@gmail.com', NULL)
SET IDENTITY_INSERT [dbo].[UserInformation] OFF