/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s06images;

import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author PC
 */
public class ListComboBox extends javax.swing.JFrame {

    ImageIcon bird = new ImageIcon("bird.jpg");
    ImageIcon cat = new ImageIcon("cat.jpg");
    ImageIcon dog = new ImageIcon("dog.jpg");
    ImageIcon rabbit = new ImageIcon("rabbit.jpg");
    ImageIcon pig = new ImageIcon("pig.jpg");

    public ListComboBox() {
        initComponents();
        this.setTitle("Luu Phuong Uyen");
        this.setSize(1000, 600);
        Image image1 = bird.getImage();
        Image iconBird = image1.getScaledInstance(400, 400, java.awt.Image.SCALE_SMOOTH);
        bird = new ImageIcon(iconBird);
        Image image2 = cat.getImage();
        Image iconCat = image2.getScaledInstance(500, 400, java.awt.Image.SCALE_SMOOTH);
        cat = new ImageIcon(iconCat);
        Image image3 = dog.getImage();
        Image iconDog = image3.getScaledInstance(500, 400, java.awt.Image.SCALE_SMOOTH);
        dog = new ImageIcon(iconDog);
        Image image4 = rabbit.getImage();
        Image iconRabbit = image4.getScaledInstance(400, 400, java.awt.Image.SCALE_SMOOTH);
        rabbit = new ImageIcon(iconRabbit);
        Image image5 = pig.getImage();
        Image iconPig = image5.getScaledInstance(400, 400, java.awt.Image.SCALE_SMOOTH);
        pig = new ImageIcon(iconPig);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pControl = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        lbView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(630, 481));

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(207, 102));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(792, 550));

        pControl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP), "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 51, 255))); // NOI18N
        pControl.setPreferredSize(new java.awt.Dimension(160, 630));
        pControl.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bird", "Cat", "Dog", "Rabbit", "Pig" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        pControl.add(jComboBox1);
        jComboBox1.setBounds(44, 300, 70, 22);

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bird", "Cat", "Dog", "Rabbit", "Pig" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        pControl.add(jScrollPane1);
        jScrollPane1.setBounds(40, 30, 80, 210);

        jSplitPane1.setLeftComponent(pControl);

        lbView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 51, 255))); // NOI18N
        jSplitPane1.setRightComponent(lbView);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String choose = jComboBox1.getSelectedItem().toString();
        if (choose.equals("Bird")) {
            lbView.setIcon(bird);
        }
        if (choose.equals("Cat")) {
            lbView.setIcon(cat);
        }
        if (choose.equals("Dog")) {
            lbView.setIcon(dog);
        }
        if (choose.equals("Rabbit")) {
            lbView.setIcon(rabbit);
        }
        if (choose.equals("Pig")) {
            lbView.setIcon(pig);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        // TODO add your handling code here:
        Object choose = jList.getSelectedValue();
        if (choose.toString().equals("Bird")) {
            lbView.setIcon(bird);
        }
        if (choose.toString().equals("Cat")) {
            lbView.setIcon(cat);
        }
        if (choose.toString().equals("Dog")) {
            lbView.setIcon(dog);
        }
        if (choose.toString().equals("Rabbit")) {
            lbView.setIcon(rabbit);
        }
        if (choose.toString().equals("Pig")) {
            lbView.setIcon(pig);
        }
    }//GEN-LAST:event_jListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListComboBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListComboBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListComboBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListComboBox.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbView;
    private javax.swing.JPanel pControl;
    // End of variables declaration//GEN-END:variables
}
