/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s122colorslider;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class ColorSlider extends javax.swing.JFrame {

    private int R = 0;
    private int G = 0;
    private int B = 0;

    public ColorSlider() {
        initComponents();
        this.setTitle("Luu Phuong Uyen");
        lbRed.setText("R = 0");
        lbRed.setForeground(Color.red);
        lbGreen.setText("G = 0");
        lbGreen.setForeground(Color.green);
        lbBlue.setText("B = 0");
        lbBlue.setForeground(Color.blue);
        slRed.setValue(0);
        slGreen.setValue(0);
        slBlue.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        slRed = new javax.swing.JSlider();
        lbRed = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slGreen = new javax.swing.JSlider();
        lbGreen = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        slBlue = new javax.swing.JSlider();
        lbBlue = new javax.swing.JLabel();
        pColor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(839, 362));
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jPanel2.setLayout(new java.awt.BorderLayout());

        slRed.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        slRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slRedStateChanged(evt);
            }
        });
        jPanel2.add(slRed, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        lbRed.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel1.add(lbRed);

        jPanel3.setLayout(new java.awt.BorderLayout());

        slGreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        slGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slGreenStateChanged(evt);
            }
        });
        jPanel3.add(slGreen, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        lbGreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel1.add(lbGreen);

        jPanel4.setLayout(new java.awt.BorderLayout());

        slBlue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        slBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBlueStateChanged(evt);
            }
        });
        jPanel4.add(slBlue, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        lbBlue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel1.add(lbBlue);

        getContentPane().add(jPanel1);

        javax.swing.GroupLayout pColorLayout = new javax.swing.GroupLayout(pColor);
        pColor.setLayout(pColorLayout);
        pColorLayout.setHorizontalGroup(
            pColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pColorLayout.setVerticalGroup(
            pColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        getContentPane().add(pColor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slRedStateChanged
        // TODO add your handling code here:
        Color color = new Color(R, G, B);
        slRed.setMaximum(255);
        R = slRed.getValue();
        lbRed.setText("R = " + R);
        pColor.setBackground(color);
    }//GEN-LAST:event_slRedStateChanged

    private void slBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBlueStateChanged
        // TODO add your handling code here:
        Color color = new Color(R, G, B);
        slBlue.setMaximum(255);
        B = slBlue.getValue();
        lbBlue.setText("B = " + B);
        pColor.setBackground(color);
    }//GEN-LAST:event_slBlueStateChanged

    private void slGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slGreenStateChanged
        // TODO add your handling code here:
        Color color = new Color(R, G, B);
        slGreen.setMaximum(255);
        G = slGreen.getValue();
        lbGreen.setText("G = " + G);
        pColor.setBackground(color);
    }//GEN-LAST:event_slGreenStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbBlue;
    private javax.swing.JLabel lbGreen;
    private javax.swing.JLabel lbRed;
    private javax.swing.JPanel pColor;
    private javax.swing.JSlider slBlue;
    private javax.swing.JSlider slGreen;
    private javax.swing.JSlider slRed;
    // End of variables declaration//GEN-END:variables
}
