/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s102digitalclock;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Luu Phuong Uyen
 */
public class DigitalLock extends javax.swing.JFrame {

    Thread t = null;
    int hours = 0, minutes = 0, seconds = 0;
    String time = "";

    class DigitalClock implements Runnable {

        DigitalClock() {
            t = new Thread(this);
            t.start();
        }

        @Override
        public void run() {
            try {
                while (true) {
                    Calendar c = Calendar.getInstance();
                    hours = c.get(Calendar.HOUR_OF_DAY);
                    if (hours > 12) {
                        hours -= 12;
                    }
                    minutes = c.get(Calendar.MINUTE);
                    seconds = c.get(Calendar.SECOND);
                    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
                    Date date = c.getTime();
                    time = sdf.format(date);
                    tfTime.setText(time);
                    t.sleep(1000);
                }
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(rootPane, e);
            }
        }
    }

    /**
     * Creates new form DigitalLock
     */
    public DigitalLock() {
        initComponents();
        new DigitalClock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(569, 482));

        jPanel1.setLayout(new java.awt.BorderLayout());

        tfTime.setEditable(false);
        tfTime.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        tfTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tfTime, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigitalLock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigitalLock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigitalLock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigitalLock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DigitalLock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfTime;
    // End of variables declaration//GEN-END:variables
}
