/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s105jformattextfield;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author PC
 */
public class JFormatTextField extends javax.swing.JFrame {

    /**
     * Creates new form JFormatTextField
     */
    public JFormatTextField() throws ParseException {
        initComponents();
        //number
        MaskFormatter num = new MaskFormatter("#,###.00");
        num.install((ftfNumber));
        //date
        DateFormatter df = new DateFormatter(new SimpleDateFormat("MM/dd/yyyy"));
        DefaultFormatterFactory dff = new DefaultFormatterFactory(df, df, df, df);
        ftfDate.setValue(new Date());
        ftfDate.setFormatterFactory(dff);
        //currency
        MaskFormatter cur = new MaskFormatter("$#,##0.00");
        cur.install((ftfCurrency));
        //time
        SimpleDateFormat sdf = new SimpleDateFormat("h:mm:ss a");
        String date = sdf.format(new Date());
        ftfTime.setValue(date);
        //percent
        MaskFormatter per = new MaskFormatter("#,##0%");
        per.install((ftfPercent));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ftfNumber = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        ftfDate = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ftfCurrency = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        ftfTime = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        ftfPercent = new javax.swing.JFormattedTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(561, 410));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 50, 20, 90));
        jPanel2.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Number");
        jPanel2.add(jLabel2);
        jPanel2.add(ftfNumber);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Date");
        jPanel2.add(jLabel3);
        jPanel2.add(ftfDate);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Currency");
        jPanel2.add(jLabel5);
        jPanel2.add(ftfCurrency);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Time");
        jPanel2.add(jLabel4);

        ftfTime.setEditable(false);
        jPanel2.add(ftfTime);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Percent");
        jPanel2.add(jLabel11);
        jPanel2.add(ftfPercent);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormatTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormatTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormatTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormatTextField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFormatTextField().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(JFormatTextField.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftfCurrency;
    private javax.swing.JFormattedTextField ftfDate;
    private javax.swing.JFormattedTextField ftfNumber;
    private javax.swing.JFormattedTextField ftfPercent;
    private javax.swing.JFormattedTextField ftfTime;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
