/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s119.createdatabase;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luu Phuong Uyen
 */
public class StocksTable extends javax.swing.JFrame {

    DefaultTableModel dtm;
    HashSet hs;

    /**
     * Creates new form StocksTable
     */
    public StocksTable() {
        initComponents();
        dtm = new DefaultTableModel();
        hs = new HashSet();
        try {
            String sql = "Use [FU_DB];\n"
                    + "SELECT * FROM dbo.Stocks";
            DatabaseInfo db = new DatabaseInfo();
            Connection con = db.openConnection();
            Statement statement = con.createStatement();
            statement.execute(sql);
            ResultSet rs = statement.getResultSet();
            Object[] title = {"StockID", "StockName", "Address", "DateAvailable", "Note"};
            dtm.setColumnIdentifiers(title);
            dtm.setRowCount(0);
            hs.clear();
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString(1));
                hs.add(rs.getString(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                dtm.addRow(vector);
            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void insertDB() {
        String sql = "Use[FU_DB];\n"
                + "BEGIN\n"
                + "Update dbo.Stocks\n"
                + "SET StockName=?,Address =?,DateAvailable =?,Note =?\n"
                + "Where StockID = ?;"
                + "\n end";
        try {
            DatabaseInfo db = new DatabaseInfo();
            Connection con = db.openConnection();
            PreparedStatement preparedStatement = con.prepareStatement(sql);
            preparedStatement.setString(1, (String) jTable1.getValueAt(0, 1));
            preparedStatement.setString(2, (String) jTable1.getValueAt(0, 2));
            preparedStatement.setString(3, (String) jTable1.getValueAt(0, 3));
            preparedStatement.setString(4, (String) jTable1.getValueAt(0, 4));
            preparedStatement.setString(5, (String) jTable1.getValueAt(0, 0));
            preparedStatement.executeUpdate();
            preparedStatement.setString(1, (String) jTable1.getValueAt(1, 1));
            preparedStatement.setString(2, (String) jTable1.getValueAt(1, 2));
            preparedStatement.setString(3, (String) jTable1.getValueAt(1, 3));
            preparedStatement.setString(4, (String) jTable1.getValueAt(1, 4));
            preparedStatement.setString(5, (String) jTable1.getValueAt(1, 0));
            preparedStatement.executeUpdate();
            preparedStatement.setString(1, (String) jTable1.getValueAt(2, 1));
            preparedStatement.setString(2, (String) jTable1.getValueAt(2, 2));
            preparedStatement.setString(3, (String) jTable1.getValueAt(2, 3));
            preparedStatement.setString(4, (String) jTable1.getValueAt(2, 4));
            preparedStatement.setString(5, (String) jTable1.getValueAt(2, 0));
            preparedStatement.executeUpdate();
            preparedStatement.setString(1, (String) jTable1.getValueAt(3, 1));
            preparedStatement.setString(2, (String) jTable1.getValueAt(3, 2));
            preparedStatement.setString(3, (String) jTable1.getValueAt(3, 3));
            preparedStatement.setString(4, (String) jTable1.getValueAt(3, 4));
            preparedStatement.setString(5, (String) jTable1.getValueAt(3, 0));
            preparedStatement.executeUpdate();
            preparedStatement.setString(1, (String) jTable1.getValueAt(4, 1));
            preparedStatement.setString(2, (String) jTable1.getValueAt(4, 2));
            preparedStatement.setString(3, (String) jTable1.getValueAt(4, 3));
            preparedStatement.setString(4, (String) jTable1.getValueAt(4, 4));
            preparedStatement.setString(5, (String) jTable1.getValueAt(4, 0));
            preparedStatement.executeUpdate();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInsertDB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));
        setPreferredSize(new java.awt.Dimension(450, 350));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 15, 5));

        btnInsertDB.setText("Insert to DB");
        btnInsertDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertDB);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertDBActionPerformed
        // TODO add your handling code here:
        try {
            insertDB();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnInsertDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StocksTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StocksTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StocksTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StocksTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StocksTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertDB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
