/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s124simplepaint;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author PC
 */
public class SimplePaint extends javax.swing.JFrame {

    /**
     * Creates new form SimplePaint
     */
    int x1, x2, y1, y2;
    Graphics g;

    public SimplePaint() {
        initComponents();
        g = pPaint.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPaint = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbBlack = new javax.swing.JLabel();
        lbBlue = new javax.swing.JLabel();
        lbPurple = new javax.swing.JLabel();
        lbRed = new javax.swing.JLabel();
        lbYellow = new javax.swing.JLabel();
        lbGreen = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pPaint.setBackground(new java.awt.Color(255, 255, 255));
        pPaint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pPaintMouseDragged(evt);
            }
        });
        pPaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pPaintMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pPaintLayout = new javax.swing.GroupLayout(pPaint);
        pPaint.setLayout(pPaintLayout);
        pPaintLayout.setHorizontalGroup(
            pPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        pPaintLayout.setVerticalGroup(
            pPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 1, 1));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        lbBlack.setBackground(new java.awt.Color(0, 0, 0));
        lbBlack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBlack.setName("lbBlack"); // NOI18N
        lbBlack.setOpaque(true);
        lbBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBlackMouseClicked(evt);
            }
        });
        jPanel2.add(lbBlack);

        lbBlue.setBackground(new java.awt.Color(0, 0, 255));
        lbBlue.setForeground(new java.awt.Color(0, 0, 255));
        lbBlue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBlue.setName("lbRed"); // NOI18N
        lbBlue.setOpaque(true);
        lbBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBlueMouseClicked(evt);
            }
        });
        jPanel2.add(lbBlue);

        lbPurple.setBackground(new java.awt.Color(128, 0, 128));
        lbPurple.setForeground(new java.awt.Color(128, 0, 128));
        lbPurple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPurple.setName("lbPurple"); // NOI18N
        lbPurple.setOpaque(true);
        lbPurple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPurpleMouseClicked(evt);
            }
        });
        jPanel2.add(lbPurple);

        lbRed.setBackground(new java.awt.Color(255, 0, 0));
        lbRed.setForeground(new java.awt.Color(255, 0, 0));
        lbRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRed.setName("lbRed"); // NOI18N
        lbRed.setOpaque(true);
        lbRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRedMouseClicked(evt);
            }
        });
        jPanel2.add(lbRed);

        lbYellow.setBackground(new java.awt.Color(255, 255, 0));
        lbYellow.setForeground(new java.awt.Color(255, 255, 255));
        lbYellow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbYellow.setName("lbRed"); // NOI18N
        lbYellow.setOpaque(true);
        lbYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbYellowMouseClicked(evt);
            }
        });
        jPanel2.add(lbYellow);

        lbGreen.setBackground(new java.awt.Color(0, 255, 0));
        lbGreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGreen.setName("lbRed"); // NOI18N
        lbGreen.setOpaque(true);
        lbGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbGreenMouseClicked(evt);
            }
        });
        jPanel2.add(lbGreen);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("CLEAR");
        clear.setName("clear"); // NOI18N
        clear.setOpaque(true);
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        jPanel2.add(clear);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_clearMouseClicked

    private void pPaintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPaintMousePressed
        // TODO add your handling code here:
        x1 = evt.getX();
        y1 = evt.getY();
    }//GEN-LAST:event_pPaintMousePressed

    private void pPaintMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPaintMouseDragged
        // TODO add your handling code here:
        x2 = evt.getX();
        y2 = evt.getY();
        if (g != null) {
            g.drawLine(x1, y1, x2, y2);
            x1 = x2;
            y1 = y2;
        }
    }//GEN-LAST:event_pPaintMouseDragged

    private void lbBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBlackMouseClicked
        // TODO add your handling code here:
        g.setColor(Color.BLACK);
    }//GEN-LAST:event_lbBlackMouseClicked

    private void lbBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBlueMouseClicked
        // TODO add your handling code here:
        g.setColor(Color.BLUE);
    }//GEN-LAST:event_lbBlueMouseClicked

    private void lbPurpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPurpleMouseClicked
        // TODO add your handling code here:
        g.setColor(new Color(128, 0, 128));
    }//GEN-LAST:event_lbPurpleMouseClicked

    private void lbRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRedMouseClicked
        // TODO add your handling code here:
        g.setColor(Color.RED);
    }//GEN-LAST:event_lbRedMouseClicked

    private void lbYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbYellowMouseClicked
        // TODO add your handling code here:
        g.setColor(Color.YELLOW);
    }//GEN-LAST:event_lbYellowMouseClicked

    private void lbGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGreenMouseClicked
        // TODO add your handling code here:
        g.setColor(Color.GREEN);
    }//GEN-LAST:event_lbGreenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimplePaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimplePaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbBlack;
    private javax.swing.JLabel lbBlue;
    private javax.swing.JLabel lbGreen;
    private javax.swing.JLabel lbPurple;
    private javax.swing.JLabel lbRed;
    private javax.swing.JLabel lbYellow;
    private javax.swing.JPanel pPaint;
    // End of variables declaration//GEN-END:variables
}
