/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2l22simplecalculator;


/**
 *
 * @author Luu Phuong Uyen
 */
public class SimpleCalculator extends javax.swing.JFrame {

    private final Operation o;

    public SimpleCalculator() {
        initComponents();
        o = new Operation();
        this.setTitle("Calculator");
        btnSqrt.setText("\u221A");
        setLocation(800, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfDisplay = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnMC = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        btnMSub = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnInverse = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(375, 495));
        setPreferredSize(new java.awt.Dimension(375, 495));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 30, 10));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tfDisplay.setEditable(false);
        tfDisplay.setBackground(new java.awt.Color(223, 255, 221));
        tfDisplay.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tfDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDisplay.setText("0");
        tfDisplay.setPreferredSize(new java.awt.Dimension(68, 50));
        jPanel1.add(tfDisplay, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.GridLayout(0, 5, 10, 10));

        btnMC.setBackground(new java.awt.Color(255, 184, 0));
        btnMC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMC.setText("MC");
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });
        jPanel2.add(btnMC);

        btnMR.setBackground(new java.awt.Color(255, 184, 0));
        btnMR.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMR.setText("MR");
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });
        jPanel2.add(btnMR);

        btnMAdd.setBackground(new java.awt.Color(255, 184, 0));
        btnMAdd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMAdd.setText("M+");
        btnMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnMAdd);

        btnMSub.setBackground(new java.awt.Color(255, 184, 0));
        btnMSub.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMSub.setText("M-");
        btnMSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSubActionPerformed(evt);
            }
        });
        jPanel2.add(btnMSub);

        btnClear.setBackground(new java.awt.Color(255, 77, 77));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);

        btn7.setBackground(new java.awt.Color(102, 153, 255));
        btn7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setBackground(new java.awt.Color(102, 153, 255));
        btn8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setBackground(new java.awt.Color(102, 153, 255));
        btn9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        btnDiv.setBackground(new java.awt.Color(92, 214, 92));
        btnDiv.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        jPanel2.add(btnDiv);

        btnSqrt.setBackground(new java.awt.Color(92, 214, 92));
        btnSqrt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });
        jPanel2.add(btnSqrt);

        btn4.setBackground(new java.awt.Color(102, 153, 255));
        btn4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setBackground(new java.awt.Color(102, 153, 255));
        btn5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setBackground(new java.awt.Color(102, 153, 255));
        btn6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btnMul.setBackground(new java.awt.Color(92, 214, 92));
        btnMul.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMul.setText("x");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });
        jPanel2.add(btnMul);

        btnPercent.setBackground(new java.awt.Color(92, 214, 92));
        btnPercent.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setMinimumSize(new java.awt.Dimension(87, 50));
        btnPercent.setPreferredSize(new java.awt.Dimension(87, 50));
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });
        jPanel2.add(btnPercent);

        btn1.setBackground(new java.awt.Color(102, 153, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setBackground(new java.awt.Color(102, 153, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setBackground(new java.awt.Color(102, 153, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btnSub.setBackground(new java.awt.Color(92, 214, 92));
        btnSub.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSub.setText("-");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        jPanel2.add(btnSub);

        btnInverse.setBackground(new java.awt.Color(92, 214, 92));
        btnInverse.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnInverse.setText("1/x");
        btnInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInverseActionPerformed(evt);
            }
        });
        jPanel2.add(btnInverse);

        btn0.setBackground(new java.awt.Color(102, 153, 255));
        btn0.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        btnDot.setBackground(new java.awt.Color(102, 153, 255));
        btnDot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        jPanel2.add(btnDot);

        btnPlusMinus.setBackground(new java.awt.Color(92, 214, 92));
        btnPlusMinus.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnPlusMinus.setText("+/-");
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlusMinus);

        btnAdd.setBackground(new java.awt.Color(92, 214, 92));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnResult.setBackground(new java.awt.Color(92, 214, 92));
        btnResult.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnResult.setText("=");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });
        jPanel2.add(btnResult);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "x"));
    }//GEN-LAST:event_btnMulActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "3"));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.MR());
    }//GEN-LAST:event_btnMRActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "1"));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "2"));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "4"));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "5"));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "6"));
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "7"));
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "8"));
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "9"));
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.InputDigit(tfDisplay.getText(), "0"));
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Dot(tfDisplay.getText()));
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInverseActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "="));
        tfDisplay.setText(o.Inverse());
    }//GEN-LAST:event_btnInverseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Clear());
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "="));
        tfDisplay.setText(o.PlusMinus());
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "+"));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "-"));
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "/"));
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        // TODO add your handling code here:
        o.MC();
    }//GEN-LAST:event_btnMCActionPerformed

    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAddActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "="));
        o.MAdd(tfDisplay.getText());
    }//GEN-LAST:event_btnMAddActionPerformed

    private void btnMSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSubActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "="));
        o.MSub(tfDisplay.getText());
    }//GEN-LAST:event_btnMSubActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "="));
        tfDisplay.setText(o.Sqrt());
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "="));
        tfDisplay.setText(o.Percent());
    }//GEN-LAST:event_btnPercentActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        tfDisplay.setText(o.Calculate(tfDisplay.getText(), "="));
    }//GEN-LAST:event_btnResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnInverse;
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMSub;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfDisplay;
    // End of variables declaration//GEN-END:variables
}
