/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2s007fontfamily;

import java.awt.Font;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author PC
 */
public class FontChooser extends javax.swing.JFrame {

    /**
     * Creates new form FontChooser
     */
    public FontChooser() {
        initComponents();
        GraphicsEnvironment g = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] fonts = g.getAllFonts();
        for (Font i : fonts) {
            cbFont.addItem(i.getFontName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbFont = new javax.swing.JComboBox<>();
        lbFontName = new javax.swing.JLabel();
        lbText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(611, 442));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 10, 40));
        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Select font family");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        jPanel1.add(jLabel1);

        cbFont.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbFont.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFontItemStateChanged(evt);
            }
        });
        jPanel1.add(cbFont);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        lbFontName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFontName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        getContentPane().add(lbFontName, java.awt.BorderLayout.CENTER);

        lbText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbText.setText("The quick brown fox jumps over the lazy dog");
        lbText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 120, 1));
        getContentPane().add(lbText, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFontItemStateChanged
        // TODO add your handling code here:
        String fontName = "";
        fontName = cbFont.getSelectedItem().toString();
        lbFontName.setText("The text is in " + fontName);
        lbFontName.setFont(new Font(fontName, 14, 18));
        lbText.setFont(new Font(fontName, 14, 18));
    }//GEN-LAST:event_cbFontItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FontChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FontChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FontChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FontChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FontChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbFont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFontName;
    private javax.swing.JLabel lbText;
    // End of variables declaration//GEN-END:variables
}
